/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrstoreman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mahdi
 */
public class AddItemsStock extends javax.swing.JFrame {

    /**
     * Creates new form AddItemsStock
     */
    public AddItemsStock() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ItemBrand = new javax.swing.JTextField();
        ItemDescription = new javax.swing.JTextField();
        ItemPurchasePrice = new javax.swing.JTextField();
        ItemWeight = new javax.swing.JTextField();
        ItemQuantity = new javax.swing.JTextField();
        jButtonInsertIntoItemTable = new javax.swing.JButton();
        jButtonBFAIS = new javax.swing.JButton();
        jLabelAISMin = new javax.swing.JLabel();
        jLabelAISClose = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ItemSellingPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ItemManufactureDate = new com.toedter.calendar.JDateChooser();
        ItemExpirationDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        AIDetails = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButtonFetchinAI = new javax.swing.JButton();
        jButtonSearchAI = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(17, 32, 65));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Brand:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Type/Description:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Purchase Price:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("weight:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Quantity:");

        ItemBrand.setBackground(new java.awt.Color(234, 67, 73));
        ItemBrand.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ItemBrand.setForeground(new java.awt.Color(240, 240, 240));

        ItemDescription.setBackground(new java.awt.Color(234, 67, 73));
        ItemDescription.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ItemDescription.setForeground(new java.awt.Color(240, 240, 240));
        ItemDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemDescriptionActionPerformed(evt);
            }
        });

        ItemPurchasePrice.setBackground(new java.awt.Color(234, 67, 73));
        ItemPurchasePrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ItemPurchasePrice.setForeground(new java.awt.Color(240, 240, 240));
        ItemPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemPurchasePriceActionPerformed(evt);
            }
        });

        ItemWeight.setBackground(new java.awt.Color(234, 67, 73));
        ItemWeight.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ItemWeight.setForeground(new java.awt.Color(240, 240, 240));
        ItemWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemWeightActionPerformed(evt);
            }
        });

        ItemQuantity.setBackground(new java.awt.Color(234, 67, 73));
        ItemQuantity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ItemQuantity.setForeground(new java.awt.Color(240, 240, 240));
        ItemQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemQuantityActionPerformed(evt);
            }
        });

        jButtonInsertIntoItemTable.setBackground(new java.awt.Color(234, 67, 73));
        jButtonInsertIntoItemTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonInsertIntoItemTable.setForeground(new java.awt.Color(240, 240, 240));
        jButtonInsertIntoItemTable.setText("Insert");
        jButtonInsertIntoItemTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertIntoItemTableActionPerformed(evt);
            }
        });

        jButtonBFAIS.setBackground(new java.awt.Color(243, 67, 73));
        jButtonBFAIS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBFAIS.setForeground(new java.awt.Color(240, 240, 240));
        jButtonBFAIS.setText("<-");
        jButtonBFAIS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBFAIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBFAISMouseClicked(evt);
            }
        });
        jButtonBFAIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBFAISActionPerformed(evt);
            }
        });

        jLabelAISMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAISMin.setForeground(new java.awt.Color(240, 240, 240));
        jLabelAISMin.setText("-");
        jLabelAISMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAISMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAISMinMouseClicked(evt);
            }
        });

        jLabelAISClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAISClose.setForeground(new java.awt.Color(240, 240, 240));
        jLabelAISClose.setText("X");
        jLabelAISClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAISClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAISCloseMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Selling Price:");

        ItemSellingPrice.setBackground(new java.awt.Color(234, 67, 73));
        ItemSellingPrice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ItemSellingPrice.setForeground(new java.awt.Color(240, 240, 240));
        ItemSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemSellingPriceActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Manufacture date:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Expiration date:");

        ItemManufactureDate.setBackground(new java.awt.Color(51, 51, 0));
        ItemManufactureDate.setForeground(new java.awt.Color(240, 240, 240));

        ItemExpirationDate.setBackground(new java.awt.Color(51, 0, 51));
        ItemExpirationDate.setForeground(new java.awt.Color(240, 240, 240));

        AIDetails.setBackground(new java.awt.Color(243, 67, 73));
        AIDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AIDetails.setForeground(new java.awt.Color(240, 240, 240));
        AIDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand", "Type/Description", "Purchase Price", "Selling Price", "Manufacture Date", "Expiration Date", "Validation Left", "Weight(gm)", "Quantity", "Status"
            }
        ));
        AIDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AIDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AIDetails);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Add new Items to Stock");

        jButtonFetchinAI.setBackground(new java.awt.Color(243, 67, 73));
        jButtonFetchinAI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFetchinAI.setForeground(new java.awt.Color(240, 240, 240));
        jButtonFetchinAI.setText("Fetch");
        jButtonFetchinAI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFetchinAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFetchinAIActionPerformed(evt);
            }
        });

        jButtonSearchAI.setBackground(new java.awt.Color(243, 67, 73));
        jButtonSearchAI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSearchAI.setForeground(new java.awt.Color(240, 240, 240));
        jButtonSearchAI.setText("Search");
        jButtonSearchAI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearchAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchAIActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(234, 67, 73));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(240, 240, 240));
        jButtonClear.setText("Clear");
        jButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearMouseClicked(evt);
            }
        });
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jButtonBFAIS)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemWeight)
                            .addComponent(ItemQuantity)
                            .addComponent(ItemSellingPrice)
                            .addComponent(ItemManufactureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemPurchasePrice)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSearchAI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ItemDescription)
                            .addComponent(ItemBrand, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAISMin)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAISClose)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonInsertIntoItemTable, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonFetchinAI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonBFAIS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ItemBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ItemDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ItemPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ItemSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemManufactureDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemExpirationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonClear)
                            .addComponent(jButtonSearchAI)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAISClose)
                            .addComponent(jLabelAISMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertIntoItemTable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFetchinAI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemDescriptionActionPerformed

    private void ItemPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemPurchasePriceActionPerformed

    private void ItemWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemWeightActionPerformed

    private void ItemQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemQuantityActionPerformed

    private void jButtonInsertIntoItemTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertIntoItemTableActionPerformed
      try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");
            //Statement stLogin = connectionLogin.createStatement();
            //String sqlLogin = "select * from Owner where OwnerEmail = ? and OwnerPassword = ?";
            //PreparedStatement pstLogin = connectionLogin.prepareStatement(sqlLogin);
            //Date date = new Date();
            //java.sql.Date joiningdate = new java.sql.Date(date.getTime());
            Date manufacturedatecheck = ItemManufactureDate.getDate();
            Date expirationdatecheck = ItemExpirationDate.getDate();
            Date presentdate = new Date();
            java.sql.Date presentdatecheck = new java.sql.Date(presentdate.getTime());
            
            float purchaseprice = Float.parseFloat(ItemPurchasePrice.getText());
            float sellingprice = Float.parseFloat(ItemSellingPrice.getText());
            
            if(manufacturedatecheck.compareTo(expirationdatecheck)>0)
            {
                JOptionPane.showMessageDialog(this,"Manufacture date can't be after the Expiration date of an item. Insert Correctly!");
            }
            
            if(expirationdatecheck.compareTo(presentdatecheck)<=0)
            {
                JOptionPane.showMessageDialog(this,"Expired product can't be added. Check expiration date!");
            }
            
            if(purchaseprice>sellingprice)
            {
                JOptionPane.showMessageDialog(this,"Purchase Price can't be higher than Selling Price");
            }
            
            if(Integer.parseInt(ItemQuantity.getText())<=0)
            {
                JOptionPane.showMessageDialog(this,"Item Quantity must be more than zero");
            }
            
           /*if(Integer.parseInt(ItemPurchasePrice.getText())>Integer.parseInt(ItemSellingPrice.getText()))
            {
                JOptionPane.showMessageDialog(this,"Purchase Price can't be higher than Selling Price");
            }*/
            
            
            if(manufacturedatecheck.compareTo(expirationdatecheck)<=0 && expirationdatecheck.compareTo(presentdatecheck)>0 && Integer.parseInt(ItemQuantity.getText())>0 &&purchaseprice<sellingprice)
            {
                String sqlInsert = "insert into Item"
                +"(ItemBrand,ItemDescription,ItemPurchasePrice,ItemSellingPrice,ItemManufactureDate,ItemExpirationDate,ItemWeight,ItemQuantity,ItemStatus)"
                +"values(?,?,?,?,?,?,?,?,?)";
            
                PreparedStatement pst = con.prepareStatement(sqlInsert);
                pst.setString(1, ItemBrand.getText());
                pst.setString(2, ItemDescription.getText());
                pst.setFloat(3, purchaseprice);
                pst.setFloat(4, sellingprice);
                
                //pst.setString(5, ItemManufactureDate.getDateFormatString());
                SimpleDateFormat mdf = new SimpleDateFormat("yyyy-MM-dd");
                String manufacturedate = mdf.format(ItemManufactureDate.getDate());
            /**/pst.setString(5, manufacturedate);
                
                //pst.setString(6, ItemExpirationDate.getDateFormatString());
                SimpleDateFormat edf = new SimpleDateFormat("yyyy-MM-dd");
                String expirationdate = edf.format(ItemExpirationDate.getDate());
            /**/pst.setString(6, expirationdate);
                
                pst.setString(7, ItemWeight.getText());
                pst.setString(8, ItemQuantity.getText());
                pst.setString(9, "Available");
                

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Item insert into stock Successfully");
            }


            //connectionLogin.close();

        }
        catch (Exception e) {
            //e.printStackTrace();
            //System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null,e);
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButtonInsertIntoItemTableActionPerformed

    private void jButtonBFAISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBFAISMouseClicked
        ItemInfo ii3 = new ItemInfo();
        ii3.setVisible(true);
        ii3.pack();
        ii3.setLocationRelativeTo(null);
        ii3.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButtonBFAISMouseClicked

    private void jButtonBFAISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBFAISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBFAISActionPerformed

    private void jLabelAISMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAISMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelAISMinMouseClicked

    private void jLabelAISCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAISCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelAISCloseMouseClicked

    private void ItemSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemSellingPriceActionPerformed

    private void jButtonFetchinAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFetchinAIActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");
            
            /*Date md = new Date();
            java.sql.Date mdate = new java.sql.Date(md.getTime());
            System.out.println(md);
            System.out.println(mdate);
            
            Date ed = new Date();
            java.sql.Date edate = new java.sql.Date(ed.getTime());
            System.out.println(ed);
            System.out.println(edate);


            String seconddate = "2021-03-20";
            Date date2=new SimpleDateFormat("yyyy-MM-dd").parse(seconddate);
            java.sql.Date newdate = new java.sql.Date(date2.getTime());
            System.out.println(seconddate+"\t"+date2);
            System.out.println(seconddate+"\t"+newdate);
            
            System.out.println("manufacture date = "+mdate);
            System.out.println("expiration date = "+edate);

            long diff = md.getTime()-ed.getTime();
            long sec = diff/1000;
            long min = sec/60;
            long hours = min/60;
            long days = hours/24;

            System.out.println("diff = "+diff);
            System.out.println("sec = "+sec);
            System.out.println("min = "+min);
            System.out.println("hours = "+hours);
            System.out.println("days = "+days);

            if(mdate.compareTo(edate)<=0)
            {
                System.out.println("Not expired");
            }

            if(mdate.compareTo(edate)>0)
            {
                System.out.println("expired");
            }*/
            
            Date date = new Date();
            java.sql.Date presentdate = new java.sql.Date(date.getTime());
            System.out.println(date);
            System.out.println(presentdate);
            
            String sqlInsert = "UPDATE Item SET Item.[ItemStatus] = 'Expired' WHERE Item.[ItemExpirationDate] <= ?;\n" +
                               "Update Item SET Item.[ItemStatus] = 'Out of stock' WHERE Item.[ItemQuantity] = 0;\n" +
                               "Update Item SET Item.[ItemStatus] = 'Available' WHERE Item.[ItemQuantity] > 0 and Item.[ItemExpirationDate] > ?;" +
                               "update Item set ItemValidationLeft = DATEDIFF(day, GETDATE(), ItemExpirationDate)";
           
            PreparedStatement pst = con.prepareStatement(sqlInsert);
            SimpleDateFormat prd = new SimpleDateFormat("yyyy-MM-dd");
            String pd = prd.format(date);
            System.out.println(pd);
            pst.setString(1, pd);
            pst.setString(2, pd);
            
            pst.executeUpdate();
            //JOptionPane.showMessageDialog(null,"Item Status updated");
            AIDetails.setModel(new DefaultTableModel(null, new String[]{"ID","Brand","Type/Description","Purchase Price","Selling Price","Manufacture Date","Expiration Date","Validation Left","Weight(gm)","Quantity","Status"}));
        }

        catch (Exception e) {
            //e.printStackTrace();
            //System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null,e);
            JOptionPane.showMessageDialog(null,e);
        }
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection2 = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");
            
            AIDetails.setModel(new DefaultTableModel(null, new String[]{"ID","Brand","Type/Description","Purchase Price","Selling Price","Manufacture Date","Expiration Date","Validation Left","Weight(gm)","Quantity","Status"}));
            Statement st2 = connection2.createStatement();
            String sql2 = "select * from Item";
            ResultSet rs2 = st2.executeQuery(sql2);
       
            Date presentdate = new Date();
            java.sql.Date presentdatecheck = new java.sql.Date(presentdate.getTime());
            SimpleDateFormat pd = new SimpleDateFormat("yyyy-MM-dd");
            String prd = pd.format(presentdatecheck);
            
            while(rs2.next()){
                String ItemId = String.valueOf(rs2.getInt("ItemId"));
                String ItemBrand = rs2.getString("ItemBrand");
                String ItemDescription = rs2.getString("ItemDescription");
                String ItemPurchasePrice = rs2.getString("ItemPurchasePrice");
                String ItemSellingPrice = rs2.getString("ItemSellingPrice");
                String ItemManufactureDate = rs2.getString("ItemManufactureDate");
                String ItemExpirationDate = rs2.getString("ItemExpirationDate");
                String ItemValidationLeft = rs2.getString("ItemValidationLeft");
                String ItemWeight = rs2.getString("ItemWeight");
                String ItemQuantity = rs2.getString("ItemQuantity");
                String ItemStatus = rs2.getString("ItemStatus");
                
                String ItemData[] = {ItemId,ItemBrand,ItemDescription,ItemPurchasePrice,ItemSellingPrice,ItemManufactureDate,ItemExpirationDate,ItemValidationLeft,ItemWeight,ItemQuantity,ItemStatus};
                DefaultTableModel items = (DefaultTableModel)AIDetails.getModel();
                items.addRow(ItemData);
            }

            connection2.close();

        }
        catch (Exception e) {
            //e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonFetchinAIActionPerformed

    private void AIDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AIDetailsMouseClicked
        int row = AIDetails.getSelectedRow();
        String selection = AIDetails.getModel().getValueAt(row,0).toString();
        //String sql = "select * from Employee where EmployeeId = " + selection;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection3 = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");
            Statement st3 = connection3.createStatement();
            String sql3 = "select * from Item where ItemId = " + selection;
            ResultSet rs3 = st3.executeQuery(sql3);
            if(rs3.next()){
                ItemBrand.setText(rs3.getString("ItemBrand"));
                ItemDescription.setText(rs3.getString("ItemDescription"));
                ItemPurchasePrice.setText(rs3.getString("ItemPurchasePrice"));
                ItemSellingPrice.setText(rs3.getString("ItemSellingPrice"));
                
                //Date manufacturedatecheck = ItemManufactureDate.getDate();
                //SimpleDateFormat mdf = new SimpleDateFormat("yyyy-MM-dd");
                //String manufacturedate = mdf.format(ItemManufactureDate.getDate());
            //**/pst.setString(5, manufacturedate);
                ItemManufactureDate.setDate(rs3.getDate("ItemManufactureDate"));
                ItemExpirationDate.setDate(rs3.getDate("ItemExpirationDate"));
                
                ItemWeight.setText(rs3.getString("ItemWeight"));
                ItemQuantity.setText(rs3.getString("ItemQuantity"));
            }

        }
        catch (Exception e) {
            //e.printStackTrace();
            //System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_AIDetailsMouseClicked

    private void jButtonSearchAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchAIActionPerformed
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");

            /*Date md = new Date();
            java.sql.Date mdate = new java.sql.Date(md.getTime());
            System.out.println(md);
            System.out.println(mdate);

            Date ed = new Date();
            java.sql.Date edate = new java.sql.Date(ed.getTime());
            System.out.println(ed);
            System.out.println(edate);

            String seconddate = "2021-03-20";
            Date date2=new SimpleDateFormat("yyyy-MM-dd").parse(seconddate);
            java.sql.Date newdate = new java.sql.Date(date2.getTime());
            System.out.println(seconddate+"\t"+date2);
            System.out.println(seconddate+"\t"+newdate);

            System.out.println("manufacture date = "+mdate);
            System.out.println("expiration date = "+edate);

            long diff = md.getTime()-ed.getTime();
            long sec = diff/1000;
            long min = sec/60;
            long hours = min/60;
            long days = hours/24;

            System.out.println("diff = "+diff);
            System.out.println("sec = "+sec);
            System.out.println("min = "+min);
            System.out.println("hours = "+hours);
            System.out.println("days = "+days);

            if(mdate.compareTo(edate)<=0)
            {
                System.out.println("Not expired");
            }

            if(mdate.compareTo(edate)>0)
            {
                System.out.println("expired");
            }*/

            Date date = new Date();
            java.sql.Date presentdate = new java.sql.Date(date.getTime());
            System.out.println(date);
            System.out.println(presentdate);

            String sqlInsert = "UPDATE Item SET Item.[ItemStatus] = 'Expired' WHERE Item.[ItemExpirationDate] <= ?;\n" +
                               "Update Item SET Item.[ItemStatus] = 'Out of stock' WHERE Item.[ItemQuantity] = 0;\n" +
                               "Update Item SET Item.[ItemStatus] = 'Available' WHERE Item.[ItemQuantity] > 0 and Item.[ItemExpirationDate] > ?;" +
                               "update Item set ItemValidationLeft = DATEDIFF(day, GETDATE(), ItemExpirationDate)";

            PreparedStatement pst = con.prepareStatement(sqlInsert);
            SimpleDateFormat prd = new SimpleDateFormat("yyyy-MM-dd");
            String pd = prd.format(date);
            System.out.println(pd);
            pst.setString(1, pd);
            pst.setString(2, pd);

            pst.executeUpdate();
            //JOptionPane.showMessageDialog(null,"Item Status updated");
            AIDetails.setModel(new DefaultTableModel(null, new String[]{"ID","Brand","Type/Description","Purchase Price","Selling Price","Manufacture Date","Expiration Date","Validation Left","Weight(gm)","Quantity","Status"}));
        }

        catch (Exception e) {
            //e.printStackTrace();
            //System.out.println(e.getMessage());
            //JOptionPane.showMessageDialog(null,e);
            JOptionPane.showMessageDialog(null,e);
        }
        
        try {
            AIDetails.setModel(new DefaultTableModel(null, new String[]{"ID","Brand","Type/Description","Purchase Price","Selling Price","Manufacture Date","Expiration Date","Validation Left","Weight(gm)","Quantity","Status"}));
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");
            
            int checkbrand=0,checkdescription=0,checkpp=0,checksp=0,checkmd=0,checked=0,checkweight=0;
            String sql1 = "SELECT * FROM Item WHERE ";
            if(ItemBrand.getText().length()>0)
            {
                sql1 +="ItemBrand LIKE '%"+ItemBrand.getText()+"%'";
                checkbrand=1;
            }

            if(ItemDescription.getText().length()>0)
            {
                if(checkbrand==0)
                {
                    sql1 += "ItemDescription LIKE '%"+ItemDescription.getText()+"%'";
                }
                else if(checkbrand==1)
                {
                    sql1 += "OR ItemDescription LIKE '%"+ItemDescription.getText()+"%'";
                }
                checkdescription=1;
            }

            if(ItemPurchasePrice.getText().length()>0)
            {
                if(checkbrand==0&&checkdescription==0)
                {
                    sql1 += "ItemPurchasePrice LIKE '%"+ItemPurchasePrice.getText()+"%'";
                }
                else if(checkbrand==1||checkdescription==1)
                {
                    sql1 += "OR ItemPurchasePrice LIKE '%"+ItemPurchasePrice.getText()+"%'";
                }
                checkpp=1;
            }

            if(ItemSellingPrice.getText().length()>0)
            {
                if(checkbrand==0&&checkdescription==0&&checkpp==0)
                {
                    sql1 += "ItemSellingPrice LIKE '%"+ItemSellingPrice.getText()+"%'";
                }
                if(checkbrand==1||checkdescription==1||checkpp==1)
                {
                    sql1 += "OR ItemSellingPrice LIKE '%"+ItemSellingPrice.getText()+"%'";
                }
                checksp=1;
            }

            if(ItemManufactureDate.getDate() != null)
            {
                Date manufacturedatecheck = ItemManufactureDate.getDate();
                SimpleDateFormat mdf = new SimpleDateFormat("yyyy-MM-dd");
                String manufacturedate = mdf.format(ItemManufactureDate.getDate());
                //**/pst.setString(5, manufacturedate);
                if(checkbrand==0&&checkdescription==0&&checkpp==0&&checksp==0)
                {
                    sql1 += "ItemManufactureDate LIKE '%"+manufacturedate+"%'";
                }
                if(checkbrand==1||checkdescription==1||checkpp==1||checksp==1)
                {
                    sql1 += "OR ItemManufactureDate LIKE '%"+manufacturedate+"%'";
                }
                checkmd=1;
            }

            if(ItemExpirationDate.getDate() != null)
            {
                Date expirationdatecheck = ItemExpirationDate.getDate();
                SimpleDateFormat edf = new SimpleDateFormat("yyyy-MM-dd");
                String expirationdate = edf.format(ItemExpirationDate.getDate());
                //**/pst.setString(6, expirationdate);
                if(checkbrand==0&&checkdescription==0&&checkpp==0&&checksp==0&&checkmd==0)
                {
                    sql1 += "ItemExpirationDate LIKE '%"+expirationdate+"%'";
                }
                if(checkbrand==1||checkdescription==1||checkpp==1||checksp==1||checkmd==1)
                {
                    sql1 += "OR ItemExpirationDate LIKE '%"+expirationdate+"%'";
                }
                checked=1;
            }

            if(ItemWeight.getText().length()>0)
            {
                if(checkbrand==0&&checkdescription==0&&checkpp==0&&checksp==0&&checkmd==0&&checked==0)
                {
                    sql1 += "ItemWeight LIKE '%"+ItemWeight.getText()+"%'";
                }
                if(checkbrand==1||checkdescription==1||checkpp==1||checksp==1||checkmd==1||checked==1)
                {
                    sql1 += "OR ItemWeight LIKE '%"+ItemWeight.getText()+"%'";
                }
                checkweight=1;
            }

            if(ItemQuantity.getText().length()>0)
            {
                if(checkbrand==0&&checkdescription==0&&checkpp==0&&checksp==0&&checkmd==0&&checked==0&&checkweight==0)
                {
                    sql1 += "ItemQuantity LIKE '%"+ItemQuantity.getText()+"%'";
                }
                if(checkbrand==1||checkdescription==1||checkpp==1||checksp==1||checkmd==1||checked==1||checkweight==1)
                {
                    sql1 += "OR ItemQuantity LIKE '%"+ItemQuantity.getText()+"%'";
                }
            }

            //sql1 += "AND EmployeeQuittingDate = 'In Contract' ";

            System.out.println("sql query is "+sql1);

            PreparedStatement pst = connection.prepareStatement(sql1);
            ResultSet rs1 = pst.executeQuery();

            while(rs1.next()){
                String ItemId = String.valueOf(rs1.getInt("ItemId"));
                String ItemBrand = rs1.getString("ItemBrand");
                String ItemDescription = rs1.getString("ItemDescription");
                String ItemPurchasePrice = rs1.getString("ItemPurchasePrice");
                String ItemSellingPrice = rs1.getString("ItemSellingPrice");
                String ItemManufactureDate = rs1.getString("ItemManufactureDate");
                String ItemExpirationDate = rs1.getString("ItemExpirationDate");
                String ItemValidationLeft = rs1.getString("ItemValidationLeft");
                String ItemWeight = rs1.getString("ItemWeight");
                String ItemQuantity = rs1.getString("ItemQuantity");
                String ItemStatus = rs1.getString("ItemStatus");

                String ItemData[] = {ItemId,ItemBrand,ItemDescription,ItemPurchasePrice,ItemSellingPrice,ItemManufactureDate,ItemExpirationDate,ItemValidationLeft,ItemWeight,ItemQuantity,ItemStatus};
                DefaultTableModel items = (DefaultTableModel)AIDetails.getModel();
                items.addRow(ItemData);
            }

            //connection.close();

        }
        catch (Exception e) {
            //e.printStackTrace();
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonSearchAIActionPerformed

    private void jButtonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearMouseClicked
        ItemBrand.setText("");
        ItemDescription.setText("");
        ItemPurchasePrice.setText("");
        ItemSellingPrice.setText("");
        ItemManufactureDate.setDate(null);
        ItemExpirationDate.setDate(null);
        ItemWeight.setText("");
        ItemQuantity.setText("");
    }//GEN-LAST:event_jButtonClearMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItemsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItemsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItemsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItemsStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItemsStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AIDetails;
    private javax.swing.JTextField ItemBrand;
    private javax.swing.JTextField ItemDescription;
    private com.toedter.calendar.JDateChooser ItemExpirationDate;
    private com.toedter.calendar.JDateChooser ItemManufactureDate;
    private javax.swing.JTextField ItemPurchasePrice;
    private javax.swing.JTextField ItemQuantity;
    private javax.swing.JTextField ItemSellingPrice;
    private javax.swing.JTextField ItemWeight;
    private javax.swing.JButton jButtonBFAIS;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonFetchinAI;
    private javax.swing.JButton jButtonInsertIntoItemTable;
    private javax.swing.JButton jButtonSearchAI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAISClose;
    private javax.swing.JLabel jLabelAISMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
