/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrstoreman;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static mrstoreman.Login2.employeeid;
import static mrstoreman.Login2.employeename;

/**
 *
 * @author Mahdi
 */
public class CustomerDetails2 extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDetails2
     */
    public CustomerDetails2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCustomerDetails2 = new javax.swing.JTable();
        jButtonFetchinCD2 = new javax.swing.JButton();
        jButtonBFCD2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelCD2Min = new javax.swing.JLabel();
        jLabelCD2Close = new javax.swing.JLabel();
        CustomerDetails2SearchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(17, 32, 65));

        jTableCustomerDetails2 = new JTable()
        {
            public boolean isCellEditable(int row, int column)
            {
                for(int i=0 ; i<jTableCustomerDetails2.getRowCount() ;i++)
                {
                    if(row == i)
                    {
                        return false;
                    }
                }
                return true;
            }
        };
        jTableCustomerDetails2.setBackground(new java.awt.Color(243, 67, 73));
        jTableCustomerDetails2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableCustomerDetails2.setForeground(new java.awt.Color(240, 240, 240));
        jTableCustomerDetails2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Contact", "Email", "Password", "Location"
            }
        ));
        jTableCustomerDetails2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCustomerDetails22MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCustomerDetails2);

        jButtonFetchinCD2.setBackground(new java.awt.Color(243, 67, 73));
        jButtonFetchinCD2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonFetchinCD2.setForeground(new java.awt.Color(240, 240, 240));
        jButtonFetchinCD2.setText("Fetch");
        jButtonFetchinCD2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFetchinCD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFetchinCD2MouseClicked(evt);
            }
        });
        jButtonFetchinCD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFetchinCD2ActionPerformed(evt);
            }
        });

        jButtonBFCD2.setBackground(new java.awt.Color(243, 67, 73));
        jButtonBFCD2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBFCD2.setForeground(new java.awt.Color(240, 240, 240));
        jButtonBFCD2.setText("<-");
        jButtonBFCD2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBFCD2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBFCD2MouseClicked(evt);
            }
        });
        jButtonBFCD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBFCD2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Customer Data");

        jLabelCD2Min.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCD2Min.setForeground(new java.awt.Color(240, 240, 240));
        jLabelCD2Min.setText("-");
        jLabelCD2Min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCD2Min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCD2MinMouseClicked(evt);
            }
        });

        jLabelCD2Close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCD2Close.setForeground(new java.awt.Color(240, 240, 240));
        jLabelCD2Close.setText("X");
        jLabelCD2Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCD2Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCD2CloseMouseClicked(evt);
            }
        });

        CustomerDetails2SearchField.setBackground(new java.awt.Color(234, 67, 73));
        CustomerDetails2SearchField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        CustomerDetails2SearchField.setForeground(new java.awt.Color(240, 240, 240));
        CustomerDetails2SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerDetails2SearchFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBFCD2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(262, 262, 262)
                        .addComponent(jLabelCD2Min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCD2Close)
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CustomerDetails2SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonFetchinCD2)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelCD2Close)
                    .addComponent(jLabelCD2Min)
                    .addComponent(jButtonBFCD2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFetchinCD2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerDetails2SearchField))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCustomerDetails22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCustomerDetails22MouseClicked

    }//GEN-LAST:event_jTableCustomerDetails22MouseClicked

    private void jButtonFetchinCD2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFetchinCD2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFetchinCD2MouseClicked

    private void jButtonFetchinCD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFetchinCD2ActionPerformed
        if(CustomerDetails2SearchField.getText().length()==0)
        {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection3 = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");
                jTableCustomerDetails2.setModel(new DefaultTableModel(null, new String[]{"ID","Name","Contact","Email","Password","Location"}));
                Statement st3 = connection3.createStatement();
                String sql3 = "select * from Customer";
                ResultSet rs3 = st3.executeQuery(sql3);
                while(rs3.next()){
                    String CustomerId = String.valueOf(rs3.getInt("CustomerId"));
                    String CustomerName = rs3.getString("CustomerName");
                    String CustomerContact = rs3.getString("CustomerContact");
                    String CustomerEmail = rs3.getString("CustomerEmail");
                    String CustomerPassword = rs3.getString("CustomerPassword");
                    String CustomerLocation = rs3.getString("CustomerLocation");

                    String CustomerData[] = {CustomerId,CustomerName,CustomerContact,CustomerEmail,CustomerPassword,CustomerLocation};
                    DefaultTableModel CTM = (DefaultTableModel)jTableCustomerDetails2.getModel();
                    CTM.addRow(CustomerData);
                }

                connection3.close();
            }
            catch (Exception e) {
                //e.printStackTrace();
                System.out.println(e.getMessage());
            }
        }

        else
        {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection3 = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=MrStoreMan;selectMethod=cursor", "sa", "123456");
                jTableCustomerDetails2.setModel(new DefaultTableModel(null, new String[]{"ID","Name","Contact","Email","Password","Location"}));
                Statement st3 = connection3.createStatement();
                String sql3 = "select * from Customer WHERE CustomerId LIKE '%"+CustomerDetails2SearchField.getText()+"%'";
                sql3 += "UNION select * from Customer WHERE CustomerName LIKE '%"+CustomerDetails2SearchField.getText()+"%'";
                sql3 += "UNION select * from Customer WHERE CustomerContact LIKE '%"+CustomerDetails2SearchField.getText()+"%'";
                sql3 += "UNION select * from Customer WHERE CustomerEmail LIKE '%"+CustomerDetails2SearchField.getText()+"%'";
                sql3 += "UNION select * from Customer WHERE CustomerPassword LIKE '%"+CustomerDetails2SearchField.getText()+"%'";
                sql3 += "UNION select * from Customer WHERE CustomerLocation LIKE '%"+CustomerDetails2SearchField.getText()+"%'";
                ResultSet rs3 = st3.executeQuery(sql3);
                while(rs3.next()){
                    String CustomerId = String.valueOf(rs3.getInt("CustomerId"));
                    String CustomerName = rs3.getString("CustomerName");
                    String CustomerContact = rs3.getString("CustomerContact");
                    String CustomerEmail = rs3.getString("CustomerEmail");
                    String CustomerPassword = rs3.getString("CustomerPassword");
                    String CustomerLocation = rs3.getString("CustomerLocation");

                    String CustomerData[] = {CustomerId,CustomerName,CustomerContact,CustomerEmail,CustomerPassword,CustomerLocation};
                    DefaultTableModel CTM = (DefaultTableModel)jTableCustomerDetails2.getModel();
                    CTM.addRow(CustomerData);
                }

                connection3.close();

            }
            catch (Exception e) {
                //e.printStackTrace();
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonFetchinCD2ActionPerformed

    private void jButtonBFCD2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBFCD2MouseClicked
        /* OwnerInterface oi3 = new OwnerInterface();
        oi3.setVisible(true);
        oi3.pack();
        oi3.setLocationRelativeTo(null);
        oi3.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();*/
        /*******************/ new EmployeeInterface(employeeid,employeename).setVisible(true); /*******************/
        this.dispose();
    }//GEN-LAST:event_jButtonBFCD2MouseClicked

    private void jButtonBFCD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBFCD2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonBFCD2ActionPerformed

    private void jLabelCD2MinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCD2MinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelCD2MinMouseClicked

    private void jLabelCD2CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCD2CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCD2CloseMouseClicked

    private void CustomerDetails2SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerDetails2SearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerDetails2SearchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDetails2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerDetails2SearchField;
    private javax.swing.JButton jButtonBFCD2;
    private javax.swing.JButton jButtonFetchinCD2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCD2Close;
    private javax.swing.JLabel jLabelCD2Min;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCustomerDetails2;
    // End of variables declaration//GEN-END:variables
}
