/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mrstoreman;

import javax.swing.JFrame;
import static mrstoreman.Login.username;

/**
 *
 * @author Mahdi
 */
public class Developers extends javax.swing.JFrame {

    /**
     * Creates new form Developers
     */
    public Developers() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserName1 = new javax.swing.JLabel();
        jLabelUserName2 = new javax.swing.JLabel();
        jLabelUserName3 = new javax.swing.JLabel();
        jLabelUserName4 = new javax.swing.JLabel();
        jLabelUserName5 = new javax.swing.JLabel();
        jLabelUserName7 = new javax.swing.JLabel();
        jLabelUserName8 = new javax.swing.JLabel();
        jButtonBFDetails = new javax.swing.JButton();
        jLabelDetailsMin = new javax.swing.JLabel();
        jLabelDetailsClose = new javax.swing.JLabel();
        jLabelUserName9 = new javax.swing.JLabel();
        jLabelUserName10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(234, 67, 73));
        jPanel1.setForeground(new java.awt.Color(234, 67, 73));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("____________________________");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("________________________");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("______________");

        jLabel6.setIcon(new javax.swing.ImageIcon("F:\\Java\\MrStoreMan\\images\\Mr.StoreManLogo.png")); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );

        jPanel2.setBackground(new java.awt.Color(17, 32, 65));
        jPanel2.setForeground(new java.awt.Color(17, 32, 65));

        jLabelUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName.setText("H.M. Mahdi Hassan Khan");

        jLabelUserName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName1.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName1.setText("Peom Dutta");

        jLabelUserName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName2.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName2.setText("ID:");

        jLabelUserName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName3.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName3.setText("18.01.04.018");

        jLabelUserName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName4.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName4.setText("18.01.04.017");

        jLabelUserName5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName5.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName5.setText("ID:");

        jLabelUserName7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName7.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName7.setText("Ahsanullah University of Science And Technology");

        jLabelUserName8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName8.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName8.setText("3rd Year 1st Semester");

        jButtonBFDetails.setBackground(new java.awt.Color(243, 67, 73));
        jButtonBFDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBFDetails.setForeground(new java.awt.Color(240, 240, 240));
        jButtonBFDetails.setText("<-");
        jButtonBFDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBFDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBFDetailsMouseClicked(evt);
            }
        });
        jButtonBFDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBFDetailsActionPerformed(evt);
            }
        });

        jLabelDetailsMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDetailsMin.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDetailsMin.setText("-");
        jLabelDetailsMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDetailsMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDetailsMinMouseClicked(evt);
            }
        });

        jLabelDetailsClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelDetailsClose.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDetailsClose.setText("X");
        jLabelDetailsClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDetailsClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDetailsCloseMouseClicked(evt);
            }
        });

        jLabelUserName9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName9.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName9.setText("Mr. Junaed Younus Khan");

        jLabelUserName10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserName10.setForeground(new java.awt.Color(240, 240, 240));
        jLabelUserName10.setText("Special thanks to our teacher & project instructor, ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelUserName7)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelUserName2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelUserName3))
                            .addComponent(jLabelUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelUserName5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelUserName4))
                            .addComponent(jLabelUserName1))
                        .addGap(28, 28, 28))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonBFDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDetailsMin)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDetailsClose))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelUserName10)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelUserName8)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelUserName9)
                        .addGap(117, 117, 117))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBFDetails)
                    .addComponent(jLabelDetailsMin)
                    .addComponent(jLabelDetailsClose))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName)
                    .addComponent(jLabelUserName1))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserName3)
                    .addComponent(jLabelUserName2)
                    .addComponent(jLabelUserName4)
                    .addComponent(jLabelUserName5))
                .addGap(44, 44, 44)
                .addComponent(jLabelUserName7)
                .addGap(34, 34, 34)
                .addComponent(jLabelUserName8)
                .addGap(48, 48, 48)
                .addComponent(jLabelUserName10)
                .addGap(41, 41, 41)
                .addComponent(jLabelUserName9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBFDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBFDetailsMouseClicked
        Start start = new Start();
        start.setVisible(true);
        start.pack();
        start.setLocationRelativeTo(null);
        start.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jButtonBFDetailsMouseClicked

    private void jButtonBFDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBFDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBFDetailsActionPerformed

    private void jLabelDetailsMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDetailsMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelDetailsMinMouseClicked

    private void jLabelDetailsCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDetailsCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelDetailsCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Developers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Developers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBFDetails;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDetailsClose;
    private javax.swing.JLabel jLabelDetailsMin;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserName1;
    private javax.swing.JLabel jLabelUserName10;
    private javax.swing.JLabel jLabelUserName2;
    private javax.swing.JLabel jLabelUserName3;
    private javax.swing.JLabel jLabelUserName4;
    private javax.swing.JLabel jLabelUserName5;
    private javax.swing.JLabel jLabelUserName7;
    private javax.swing.JLabel jLabelUserName8;
    private javax.swing.JLabel jLabelUserName9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
